language: c

env:
  global:
    # encrypted AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to push docs to s3
    - secure: "bVH6M//wxPNZSCe2DHDVxc9Umnz+7S+L5Sm+fGugQ9Nv/7lqPi/aCBRW+O7o9BgOye0s0IRr+ivyRJ5I8cYN5a2rpYsKIo/aItJ2sN/3Gw8K/6BZMjmMJFNaHUREtazpftkiv8WADZV/j5d1QcBHzx/RHyubtLerx22dgCvyc0s="
    - secure: "OFwGj26dWBFaUcHpz8BRlPw0IFcbt6827kutfpgrb19ebldKv18TvE3BXJIoKDTUz9yGhv+j1hUi64vGUTRbv5y7bAE9bK9r9/y7mFVTWHu5IRyhmewr2DuqKkNyI2bI57FbRBGVt6Nrf68tzg8QCLu8GoIutGWeHH0D1li8bZ4="


install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-dev python-pip python-yaml g++
    - sudo pip install conda
    - sudo conda init
    - conda create --yes --name test numpy scipy pytables numexpr nose pandas cython statsmodels pandas patsy pyyaml matplotlib pip
    - export PATH="$HOME/envs/test/bin/:$PATH"
    - pip install fastcluster mdtraj

    # RMG is not really sure what this line does, but it's critical for multiprocessing 
    # to work in python. see https://github.com/travis-ci/travis-cookbooks/issues/155 and
    # https://github.com/SimTk/msmbuilder/issues/214
    - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm 
    
script:
    - python setup.py install
    - nosetests -vv
