language: c
install:
    - sudo apt-get update
    - sudo apt-get install -qq python-dev python-pip python-yaml
    - sudo pip install conda
    - sudo conda init
    - conda create -n test numpy scipy pytables numexpr nose pandas cython statsmodels pandas patsy
    - source activate test
    - sudo pip install fastcluster

    # RMG is not really sure what this line does, but it's critical for multiprocessing 
    # to work in python. see https://github.com/travis-ci/travis-cookbooks/issues/155 and
    # https://github.com/SimTk/msmbuilder/issues/214
    - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm 
    
script:
    - sudo python setup.py install
    - nosetests -vv
